modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "ridehorse"
version = "1.0"
displayName = "RideHorse"
description = '''

'''

[[dependencies.ridehorse]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridehorse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
